FROM ubuntu:latest
MAINTAINER Bipin
RUN useradd bipin
RUN echo "bipin:bipin123" | chpasswd
RUN apt-get update -y && apt-get install openssh-server -y
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN /etc/init.d/ssh start
EXPOSE 22
